<?xml version="1.0" ?>
<robot name="robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- world -->
  <link name="world" />

  <!-- workcell -->
  <xacro:include filename="$(find hrwros_support)/urdf/workcell/workcell.urdf.xacro"/>
  <xacro:workcell_urdf workcell_parent="world_interface"/>

  <!-- Robot1 Pedestal -->
  <xacro:include filename="$(find hrwros_support)/urdf/robot_pedestal/robot_pedestal.urdf.xacro"/>
  <xacro:robot_pedestal_urdf pedestal_prefix="robot1_" pedestal_parent="world_interface" pedestal_height="0.95">
    <origin xyz="0.5 1.8 0.0" rpy="0 0 0"/>
  </xacro:robot_pedestal_urdf>

  <!-- Robot1 -->
  <xacro:include filename="$(find ur_description)/urdf/ur10.urdf.xacro"/>
  <xacro:ur10_robot prefix="robot1_" joint_limited="true"/>

  <!-- Vacuum Gripper1 -->
  <xacro:include filename="$(find hrwros_support)/urdf/vacuum_gripper/vacuum_gripper.urdf.xacro"/>
  <xacro:vacuum_gripper_urdf prefix="vacuum_gripper1_" joint_prefix="vacuum_gripper1_joint"/>

  <!-- bins -->
  <xacro:include filename="$(find hrwros_support)/urdf/bin/bin.urdf.xacro"/>
  <xacro:bin_urdf prefix="bin_1_"/>

  <!-- Joints -->
  <joint name="world_interface_to_world" type="fixed">
    <parent link="world" />
    <child link="world_interface" />
  </joint>

  <!-- robot1-pedestal to world. -->
  <joint name="robot1_pedestal_to_world_interface" type="fixed">
    <parent link="world_interface" />
    <child link="robot1_pedestal_link" />
    <origin xyz="0.5 1.8 0.0" rpy="0.0 0.0 0.0"/>
  </joint>

  <!-- robot1 to pedestal. -->
  <joint name="robot1_to_pedestal" type="fixed">
  <origin xyz="0 0 0.95" rpy="0 0 0" />
  <parent link="robot1_pedestal_link" />
  <child link="robot1_base_link" />
  </joint>

  <!-- gripper1 to robot1. -->
  <joint name="gripper1_to_robot1" type="fixed">
    <parent link="robot1_tool0" />
    <child link="vacuum_gripper1_base_link" />
  </joint>

  <!-- bin 1 -->
  <joint name="bin_1_joint" type="fixed">
    <parent link="world_interface" />
    <child link="bin_1_base_link" />
    <origin xyz="-8.0 -2.2 0.0" rpy="0 0 0" />
  </joint>

  <!-- robot2 pedestal properties -->
  <xacro:property name="robot2_pedestal_height" value="0.6" />

  <!-- robot2 pedestal link -->
  <link name="robot2_pedestal_link">
    <visual>
      <origin xyz="0 0 ${robot2_pedestal_height/2}" />
      <geometry>
        <box size="0.3 0.3 ${robot2_pedestal_height}" />
      </geometry>
      <material name="robot2_pedestal_color">
        <color rgba="0 0.16 0.53 1" />
      </material>
    </visual>
  </link>

  <!-- robot2 pedestal joint -->
  <joint name="robot2_pedestal_joint" type="fixed">
    <parent link="world" />
    <child link="robot2_pedestal_link" />
    <origin xyz="-7.8 -1.5 0" />
  </joint>

  <!-- robot2 model definition (xacro macro) -->
  <xacro:include filename= "$(find ur_description)/urdf/ur5.urdf.xacro" />
  <xacro:ur5_robot prefix="robot2_" joint_limited="true" />

  <!-- robot2 joint to pedestal -->
  <joint name="robot2-robot2_pedestal_joint" type="fixed">
    <parent link="robot2_pedestal_link" />
    <child link="robot2_base_link" />
    <origin xyz="0 0 ${robot2_pedestal_height}" rpy="0 0 ${radians(90)}" />
  </joint>

</robot>
